// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Buff.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace P5.Protobuf {

  /// <summary>Holder for reflection information generated from Buff.proto</summary>
  public static partial class BuffReflection {

    #region Descriptor
    /// <summary>File descriptor for Buff.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BuffReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpCdWZmLnByb3RvEgtQNS5Qcm90b2J1ZiJ0CghCdWZmRGF0YRIOCgZidWZm",
            "SWQYASABKAUSEQoJc3RhcnRUaW1lGAIgASgDEhAKCGJ1ZmZTZWNzGAMgASgF",
            "Eg8KB2J1ZmZWYWwYBCABKAMSEAoIYnVmZlR5cGUYBSABKAUSEAoIYnVmZlZh",
            "bDIYBiABKANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::P5.Protobuf.BuffData), global::P5.Protobuf.BuffData.Parser, new[]{ "BuffId", "StartTime", "BuffSecs", "BuffVal", "BuffType", "BuffVal2" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///效果
  /// </summary>
  public sealed partial class BuffData : pb::IMessage<BuffData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BuffData> _parser = new pb::MessageParser<BuffData>(() => new BuffData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BuffData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::P5.Protobuf.BuffReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BuffData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BuffData(BuffData other) : this() {
      buffId_ = other.buffId_;
      startTime_ = other.startTime_;
      buffSecs_ = other.buffSecs_;
      buffVal_ = other.buffVal_;
      buffType_ = other.buffType_;
      buffVal2_ = other.buffVal2_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BuffData Clone() {
      return new BuffData(this);
    }

    /// <summary>Field number for the "buffId" field.</summary>
    public const int BuffIdFieldNumber = 1;
    private int buffId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BuffId {
      get { return buffId_; }
      set {
        buffId_ = value;
      }
    }

    /// <summary>Field number for the "startTime" field.</summary>
    public const int StartTimeFieldNumber = 2;
    private long startTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long StartTime {
      get { return startTime_; }
      set {
        startTime_ = value;
      }
    }

    /// <summary>Field number for the "buffSecs" field.</summary>
    public const int BuffSecsFieldNumber = 3;
    private int buffSecs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BuffSecs {
      get { return buffSecs_; }
      set {
        buffSecs_ = value;
      }
    }

    /// <summary>Field number for the "buffVal" field.</summary>
    public const int BuffValFieldNumber = 4;
    private long buffVal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long BuffVal {
      get { return buffVal_; }
      set {
        buffVal_ = value;
      }
    }

    /// <summary>Field number for the "buffType" field.</summary>
    public const int BuffTypeFieldNumber = 5;
    private int buffType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BuffType {
      get { return buffType_; }
      set {
        buffType_ = value;
      }
    }

    /// <summary>Field number for the "buffVal2" field.</summary>
    public const int BuffVal2FieldNumber = 6;
    private long buffVal2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long BuffVal2 {
      get { return buffVal2_; }
      set {
        buffVal2_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BuffData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BuffData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BuffId != other.BuffId) return false;
      if (StartTime != other.StartTime) return false;
      if (BuffSecs != other.BuffSecs) return false;
      if (BuffVal != other.BuffVal) return false;
      if (BuffType != other.BuffType) return false;
      if (BuffVal2 != other.BuffVal2) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (BuffId != 0) hash ^= BuffId.GetHashCode();
      if (StartTime != 0L) hash ^= StartTime.GetHashCode();
      if (BuffSecs != 0) hash ^= BuffSecs.GetHashCode();
      if (BuffVal != 0L) hash ^= BuffVal.GetHashCode();
      if (BuffType != 0) hash ^= BuffType.GetHashCode();
      if (BuffVal2 != 0L) hash ^= BuffVal2.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BuffId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(BuffId);
      }
      if (StartTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(StartTime);
      }
      if (BuffSecs != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(BuffSecs);
      }
      if (BuffVal != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(BuffVal);
      }
      if (BuffType != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(BuffType);
      }
      if (BuffVal2 != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(BuffVal2);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BuffId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(BuffId);
      }
      if (StartTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(StartTime);
      }
      if (BuffSecs != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(BuffSecs);
      }
      if (BuffVal != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(BuffVal);
      }
      if (BuffType != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(BuffType);
      }
      if (BuffVal2 != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(BuffVal2);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BuffId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuffId);
      }
      if (StartTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(StartTime);
      }
      if (BuffSecs != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuffSecs);
      }
      if (BuffVal != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(BuffVal);
      }
      if (BuffType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuffType);
      }
      if (BuffVal2 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(BuffVal2);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BuffData other) {
      if (other == null) {
        return;
      }
      if (other.BuffId != 0) {
        BuffId = other.BuffId;
      }
      if (other.StartTime != 0L) {
        StartTime = other.StartTime;
      }
      if (other.BuffSecs != 0) {
        BuffSecs = other.BuffSecs;
      }
      if (other.BuffVal != 0L) {
        BuffVal = other.BuffVal;
      }
      if (other.BuffType != 0) {
        BuffType = other.BuffType;
      }
      if (other.BuffVal2 != 0L) {
        BuffVal2 = other.BuffVal2;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BuffId = input.ReadInt32();
            break;
          }
          case 16: {
            StartTime = input.ReadInt64();
            break;
          }
          case 24: {
            BuffSecs = input.ReadInt32();
            break;
          }
          case 32: {
            BuffVal = input.ReadInt64();
            break;
          }
          case 40: {
            BuffType = input.ReadInt32();
            break;
          }
          case 48: {
            BuffVal2 = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BuffId = input.ReadInt32();
            break;
          }
          case 16: {
            StartTime = input.ReadInt64();
            break;
          }
          case 24: {
            BuffSecs = input.ReadInt32();
            break;
          }
          case 32: {
            BuffVal = input.ReadInt64();
            break;
          }
          case 40: {
            BuffType = input.ReadInt32();
            break;
          }
          case 48: {
            BuffVal2 = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
