// <auto-generated>
//     Generated by TableExportWindow.  DO NOT EDIT!
// </auto-generated>
using System.Collections.Generic;
namespace Core.Game.Table
{
    public partial class AudiosTable
    {
        private Dictionary<string, Audios> mDic = null;
        public Audios Get(string id)
        {
            if(mDic == null)
            {
                mDic = new Dictionary<string, Audios>();
                foreach(var row in Rows)
                {
                    mDic.Add(row.UrlPath, row);
                }
            }
            mDic.TryGetValue(id, out var data);
            return data;
        }
    }
    public partial class Audios
    {
    }
}
