// <auto-generated>
//     Generated by TableExportWindow.  DO NOT EDIT!
// </auto-generated>
using System.Collections.Generic;
namespace Core.Game.Table
{
    public partial class MapTable
    {
        private Dictionary<uint, Map> mDic = null;
        public Map Get(uint id)
        {
            if(mDic == null)
            {
                mDic = new Dictionary<uint, Map>();
                foreach(var row in Rows)
                {
                    mDic.Add(row.Code, row);
                }
            }
            mDic.TryGetValue(id, out var data);
            return data;
        }
    }
    public partial class Map
    {
    }
}
