// <auto-generated>
//     Generated by TableExportWindow.  DO NOT EDIT!
// </auto-generated>
using System.Collections.Generic;
namespace Core.Game.Table
{
    public partial class MonstersTable
    {
        private Dictionary<uint, Monsters> mDic = null;
        public Monsters Get(uint id)
        {
            if(mDic == null)
            {
                mDic = new Dictionary<uint, Monsters>();
                foreach(var row in Rows)
                {
                    mDic.Add(row.ID, row);
                }
            }
            mDic.TryGetValue(id, out var data);
            return data;
        }
    }
    public partial class Monsters
    {
    }
}
