// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConfigTable.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Core.Game.Table {

  /// <summary>Holder for reflection information generated from ConfigTable.proto</summary>
  public static partial class ConfigTableReflection {

    #region Descriptor
    /// <summary>File descriptor for ConfigTable.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigTableReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFDb25maWdUYWJsZS5wcm90bxIPQ29yZS5HYW1lLlRhYmxlIksKC0NvbmZp",
            "Z1RhYmxlEgsKA0FBQRgBIAEoBRILCgNCQkIYAiABKAISCwoDQ0NDGAMgASgJ",
            "EhUKDVNwZWNpYWxNYWdpYzEYBSADKAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Core.Game.Table.ConfigTable), global::Core.Game.Table.ConfigTable.Parser, new[]{ "AAA", "BBB", "CCC", "SpecialMagic1" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigTable : pb::IMessage<ConfigTable>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ConfigTable> _parser = new pb::MessageParser<ConfigTable>(() => new ConfigTable());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigTable> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Core.Game.Table.ConfigTableReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigTable() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigTable(ConfigTable other) : this() {
      aAA_ = other.aAA_;
      bBB_ = other.bBB_;
      cCC_ = other.cCC_;
      specialMagic1_ = other.specialMagic1_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigTable Clone() {
      return new ConfigTable(this);
    }

    /// <summary>Field number for the "AAA" field.</summary>
    public const int AAAFieldNumber = 1;
    private int aAA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int AAA {
      get { return aAA_; }
      set {
        aAA_ = value;
      }
    }

    /// <summary>Field number for the "BBB" field.</summary>
    public const int BBBFieldNumber = 2;
    private float bBB_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float BBB {
      get { return bBB_; }
      set {
        bBB_ = value;
      }
    }

    /// <summary>Field number for the "CCC" field.</summary>
    public const int CCCFieldNumber = 3;
    private string cCC_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CCC {
      get { return cCC_; }
      set {
        cCC_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SpecialMagic1" field.</summary>
    public const int SpecialMagic1FieldNumber = 5;
    private static readonly pb::FieldCodec<int> _repeated_specialMagic1_codec
        = pb::FieldCodec.ForInt32(42);
    private readonly pbc::RepeatedField<int> specialMagic1_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> SpecialMagic1 {
      get { return specialMagic1_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigTable);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigTable other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AAA != other.AAA) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(BBB, other.BBB)) return false;
      if (CCC != other.CCC) return false;
      if(!specialMagic1_.Equals(other.specialMagic1_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AAA != 0) hash ^= AAA.GetHashCode();
      if (BBB != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(BBB);
      if (CCC.Length != 0) hash ^= CCC.GetHashCode();
      hash ^= specialMagic1_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AAA != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AAA);
      }
      if (BBB != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(BBB);
      }
      if (CCC.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CCC);
      }
      specialMagic1_.WriteTo(output, _repeated_specialMagic1_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AAA != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AAA);
      }
      if (BBB != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(BBB);
      }
      if (CCC.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CCC);
      }
      specialMagic1_.WriteTo(ref output, _repeated_specialMagic1_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AAA != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AAA);
      }
      if (BBB != 0F) {
        size += 1 + 4;
      }
      if (CCC.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CCC);
      }
      size += specialMagic1_.CalculateSize(_repeated_specialMagic1_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigTable other) {
      if (other == null) {
        return;
      }
      if (other.AAA != 0) {
        AAA = other.AAA;
      }
      if (other.BBB != 0F) {
        BBB = other.BBB;
      }
      if (other.CCC.Length != 0) {
        CCC = other.CCC;
      }
      specialMagic1_.Add(other.specialMagic1_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AAA = input.ReadInt32();
            break;
          }
          case 21: {
            BBB = input.ReadFloat();
            break;
          }
          case 26: {
            CCC = input.ReadString();
            break;
          }
          case 42:
          case 40: {
            specialMagic1_.AddEntriesFrom(input, _repeated_specialMagic1_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AAA = input.ReadInt32();
            break;
          }
          case 21: {
            BBB = input.ReadFloat();
            break;
          }
          case 26: {
            CCC = input.ReadString();
            break;
          }
          case 42:
          case 40: {
            specialMagic1_.AddEntriesFrom(ref input, _repeated_specialMagic1_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
